services:
  web:
    build:
      context: .
    command: 'rails s -b 0 puma'
    stop_signal: SIGINT
    ports:
      - 3000:3000
    volumes:
      - bundle_cache:/usr/local/bundle
      - node_modules:/app/node_modules
      - .:/app

volumes:
  bundle_cache:
  node_modules:

